In [5]:
import scipy.io as sio  
import matplotlib.pyplot as plt  
import numpy as np 

In [7]:
data=sio.loadmat('data1.mat')   

In [10]:
TestX=data['TestX']
TestY=data['TestY']
TrainingX=data['TrainingX']
TrainingY=data['TrainingY']

In [15]:
print(TestX.shape)
print(TestY.shape)
print(TrainingX.shape)
print(TrainingY.shape)

(1000, 784)
(1000, 1)
(10000, 784)
(10000, 1)


In [ ]:
class LogisticFun(object):
    def __init__(self,X,y):
        self.X=X
        self.y=y
        n=X.shape[0]
    
    def feval(self,w):
        z=y[i,:]*w

In [18]:
def calEuclideanDistance(vec1,vec2):  
    dist = np.sum(np.square(vec1 - vec2))  
    return dist 
dis=0
for i in range(0,784):
    for j in range(0,784):
        dis+=calEuclideanDistance(TrainingX[i,:], TrainingX[j,:])
the=dis/(np.square(1000))

print(the)

55.112240203674254


In [38]:
k = [[0 for i in range(1000)] for i in range(1000)]
k=np.array(k)

In [39]:
for i in range(0,1000):
    for j in range(0,1000):
        k[i][j]=np.exp((-1/2*np.square(the))*calEuclideanDistance(TrainingX[i,:], TrainingX[j,:]))


In [40]:
w = [[0 for i in range(1000)] for i in range(4000)]

In [43]:
w=np.array(w)
wini=w[0,:]
wini.shape

(1000,)

In [73]:
grad_his=[]
J_his=[]
s=0
gg=0
for j in range(0,999):
    for i in range(0,1000):
        z=TrainingY[i,:]*w[j,:].dot(k[:,i])
        g=1/(1+np.exp(-z))
        s+=np.log(g)
        gg+=(1-g)*TrainingY[i,:]*(k[:,i].T)
    grad=-gg+2*0.001*w[j,:]
    J=-s+0.001*w[j,:].T.dot(w[j,:])
    J_his.append(J)
    grad_his.append(grad)
    w[j+1,:]=w[j,:]+0.001*grad
#dJ_dw=-np.sum()

In [72]:
J_his


[array([693.1538], dtype=float32),
 array([1386.2982], dtype=float32),
 array([2079.4136], dtype=float32),
 array([2772.5288], dtype=float32),
 array([3465.644], dtype=float32),
 array([4158.7812], dtype=float32),
 array([4852.1406], dtype=float32),
 array([5545.5], dtype=float32),
 array([6238.8594], dtype=float32),
 array([6932.2188], dtype=float32),
 array([7625.578], dtype=float32),
 array([8318.9375], dtype=float32),
 array([9012.297], dtype=float32),
 array([9705.656], dtype=float32),
 array([10399.016], dtype=float32),
 array([11092.375], dtype=float32),
 array([11785.734], dtype=float32),
 array([12479.094], dtype=float32),
 array([13172.453], dtype=float32),
 array([13865.8125], dtype=float32),
 array([14559.172], dtype=float32),
 array([15252.531], dtype=float32),
 array([15945.891], dtype=float32),
 array([16639.25], dtype=float32),
 array([17332.61], dtype=float32),
 array([18025.969], dtype=float32),
 array([18719.328], dtype=float32),
 array([19412.688], dtype=float32),
 